const A='assets/cards/', I='assets/icons/';
const chars={felphs:{name:'FELPHS SILVERHAND',hp:280,def:0,type:'ATIRADOR',resource:'MUNIÇÃO',portrait:'file_000000009210820e9028589bab69ae7e.webp',moves:[
{id:'pente',name:'PENTE APRIMORADO',kind:'BÁSICO',damage:20,cost:1,art:'file_0000000083ec820eaaea062e71d9d193.webp',effect:'Libera Fuga Tática'},
{id:'anti',name:'ANTI BLINDAGEM',kind:'ESPECIAL',damage:35,cost:2,art:'file_00000000d380820ea35b11eee333a77e.webp',pierce:true,effect:'Quebra de armadura'},
{id:'melhor',name:'MELHOR ATIRADOR DO MUNDO',kind:'ESPECIAL',damage:40,cost:4,art:'file_00000000af88820e8185dfa7d5b1107c.webp',effect:'Queimadura: +10 no próximo golpe'},
{id:'deadshot',name:'DEADSHOT',kind:'ULTIMATE',damage:120,cost:5,once:true,pierce:true,antiFuga:true,art:'file_00000000201c820e852d51c9a8befb28.webp',effect:'Anti Fuga • Quebra de Armadura'}]},
marshall:{name:'MARSHALL B NICKO',hp:300,def:0,type:'GUERREIRO',resource:'ESTAMINA',portrait:'file_000000000108820e95b41e8cef42ae7e.webp',moves:[
{id:'corte',name:'CORTE DO CAOS',kind:'BÁSICO',damage:30,cost:2,art:'file_000000000e14820ea36895ac2c96a69d.webp',effect:'Sangramento: +20 no próximo golpe'},
{id:'puxao',name:'PUXÃO DA ÂNCORA',kind:'ESPECIAL',damage:20,cost:1,art:'file_0000000096a4820e956c59109dc78310.webp',effect:'Launcher: libera o MID'},
{id:'mid',name:'CARNIFICINA DO CAPITÃO',kind:'ESPECIAL',damage:30,cost:2,art:'file_00000000b3b0820e91890135fc14a418.webp',effect:'Somente após Launcher; libera finalização'},
{id:'final',name:'AFUNDA COM O NAVIO',kind:'ESPECIAL',damage:70,cost:3,art:'file_00000000e704820ea3466bb2aa3e9c84.webp',effect:'Somente após MID; encerra combo'},
{id:'kraken',name:'VINDA DO KRAKEN',kind:'ULTIMATE',damage:130,cost:5,once:true,art:'file_000000004fc8820e9952be8ab91a681d.webp',effect:'Devorado: desativa a passiva do alvo'}]}};
let mode='offline',chosen='felphs',game=null,sound=true,locked=false;
const $=id=>document.getElementById(id), roll=()=>Math.floor(Math.random()*6)+1;
function show(id){document.querySelectorAll('.screen').forEach(el=>el.classList.toggle('active',el.id===id))}
function popup(html){$('modal-content').innerHTML=html;$('modal').hidden=false}
function note(msg){$('announcement').textContent=msg;const log=$('log');log.innerHTML=`<div>${msg}</div>`+log.innerHTML}
function dice(n,label){$('dice-display').innerHTML=`${label} <b>${n}</b>`}
function initRoster(){const r=$('roster');r.innerHTML=Object.entries(chars).map(([id,c])=>`<button class="choice ${chosen===id?'active':''}" data-char="${id}"><img src="${A+c.portrait}" alt="${c.name}"><strong>${c.name}</strong><small>${c.type} · ${c.hp} VIDA · ${c.resource}</small></button>`).join('');r.querySelectorAll('[data-char]').forEach(btn=>btn.onclick=()=>{chosen=btn.dataset.char;initRoster()})}
function start(){const opponent=chosen==='felphs'?'marshall':'felphs';game={players:[make(chosen),make(opponent)],turn:0,round:1,phase:'action',pending:null,ended:false};show('battle');$('log').innerHTML='';$('dice-display').innerHTML='';note('Seu turno. Escolha uma ação.');render()}
function make(id){return{id,hp:chars[id].hp,def:chars[id].def,res:8,escapes:2,used:{},fugaReady:false,fugaUsed:false,miraReady:false,miraUsed:false,passiveDisabled:false,burn:0,bleed:0,combo:0,evasion:false}}
function active(){return game.players[game.turn]};function other(){return game.players[1-game.turn]}
function canUse(p,m){return p.res>=m.cost&&(!m.once||!p.used[m.id])&&(m.id!=='mid'||p.combo===1)&&(m.id!=='final'||p.combo===2)}
function render(){if(!game)return;game.players.forEach((p,i)=>{const c=chars[p.id];$(`fighter-${i?'b':'a'}`).innerHTML=`<h2>${c.name}</h2><img src="${A+c.portrait}" alt=""><div class="stats"><span>❤ ${p.hp}/${c.hp}</span><span>◆ ${p.def} DEFESA</span><span>${c.resource}: ${p.res}/8</span><span>FUGAS: ${p.escapes}/2</span></div><div class="bar"><i style="width:${100*p.hp/c.hp}%"></i></div><div class="bar resource"><i style="width:${100*p.res/8}%"></i></div><div class="stats">${p.passiveDisabled?'PASSIVA DESATIVADA':p.miraReady?'MIRA FRIA PRONTA':p.combo?'COMBO '+p.combo:''}</div>`});$('round').textContent=`· RODADA ${game.round}`;const a=$('actions');a.innerHTML='';if(game.ended)return;if(game.turn!==0&&!(game.phase==='defend'&&game.pending?.target===game.players[0])){a.innerHTML='<p>Oponente escolhendo...</p>';return}const p=game.phase==='defend'?game.pending.target:active(),c=chars[p.id],free=game.freeReturn!==undefined&&game.freeReturn!==null;if(game.phase==='defend'){a.innerHTML=`<button class="action" data-action="block"><img src="${I}BLOQUEAR.webp">BLOQUEAR <span class="tiny">D6: 4–5 metade · 6 perfeito</span></button><button class="action" data-action="take">RECEBER GOLPE</button>`;if(p.escapes>0&&!game.pending?.antiFuga&&!(game.pending?.attacker.id==='marshall'&&game.pending?.attacker.combo>0))a.innerHTML+=`<button class="action" data-action="escape"><img src="${I}FUGA.webp">FUGA <span class="tiny">${p.escapes} usos restantes</span></button>`}else{a.innerHTML=c.moves.map(m=>`<button class="action card" data-move="${m.id}" ${canUse(p,m)?'':'disabled'}><img src="${A+m.art}" alt=""><strong>${m.name}</strong><span class="tiny">${m.damage} dano · ${m.cost} ${c.resource}</span></button>`).join('');if(free)a.innerHTML+='<button class="action" data-action="pass">PULAR CONTRA-ATAQUE</button>';else{a.innerHTML+=`<button class="action" data-action="reload"><img src="${I+(p.id==='felphs'?'RECARREGAR':'FÔLEGO')}.webp">${p.id==='felphs'?'RECARREGAR':'FÔLEGO'} <span class="tiny">Restaura 8 · gasta o turno</span></button>`;if(p.id==='felphs'&&p.fugaReady&&!p.fugaUsed&&p.escapes>0)a.innerHTML+=`<button class="action" data-action="tactical"><img src="${A}file_00000000199c820ea478a799e1efbdd8.webp">FUGA TÁTICA</button>`;if(p.id==='felphs'&&p.miraReady&&!p.miraUsed&&!p.passiveDisabled)a.innerHTML+=`<button class="action" data-action="mira">MIRA FRIA <span class="tiny">4 tiros · 80 dano · sem munição</span></button>`}}a.querySelectorAll('button').forEach(b=>b.onclick=()=>b.dataset.move?chooseMove(b.dataset.move):action(b.dataset.action))}
function chooseMove(id){if(locked||game.ended||game.turn!==0||game.phase!=='action')return;const p=active(),m=chars[p.id].moves.find(x=>x.id===id);if(!m||!canUse(p,m))return;attack(p,other(),m,game.freeReturn!==undefined&&game.freeReturn!==null)}
function attack(p,t,m,free){p.res-=m.cost;if(m.once)p.used[m.id]=true;let n=p.id==='felphs'?roll():null;let damage=m.damage+(p.burn||0)+(p.bleed||0);p.burn=0;p.bleed=0;if(n!==null){dice(n,'PRECISÃO');if(n<=3){note(`${m.name}: tiro errou (D6: ${n}).`);if(free){game.freeReturn=null;game.phase='action';render();if(game.turn===1)delayed(aiAct)}else finishTurn();return}if(n===6)damage=m.damage*2+(damage-m.damage)}if(m.id==='puxao')p.combo=1;else if(m.id==='mid')p.combo=2;else if(m.id==='final')p.combo=0;else if(p.id==='marshall')p.combo=0;
game.pending={attacker:p,target:t,move:m,damage,free,antiFuga:!!m.antiFuga};game.phase='defend';note(`${p===game.players[0]?'Você usou':'Oponente usou'} ${m.name} (${damage} de dano). ${t===game.players[0]?'Escolha a defesa.':'Oponente se defende...'}`);render();if(t!==game.players[0])delayed(()=>aiDefend())}
function applyDamage(p,d,pierce){let remaining=d;if(!pierce){const absorbed=Math.min(p.def,remaining);p.def-=absorbed;remaining-=absorbed}p.hp=Math.max(0,p.hp-remaining)}
function resolveDefense(kind){if(!game||game.phase!=='defend'||game.ended)return;const x=game.pending,p=x.attacker,t=x.target,m=x.move;let damage=x.damage,perfect=false;if(kind==='tacticalEvade'){damage=0;note('FUGA TÁTICA evitou o golpe.')}else if(kind==='escape'&&!x.antiFuga&&t.escapes>0&&!(p.id==='marshall'&&p.combo>0)){t.escapes--;damage=0;note(`${chars[t.id].name} escapou do golpe. Restam ${t.escapes} fugas.`)}else if(kind==='block'&&!m.pierce){const n=roll();dice(n,'BLOQUEIO');if(n===6){damage=0;perfect=true;note('BLOQUEIO PERFEITO! Contra-ataque gratuito liberado.')}else if(n>=4){damage=Math.ceil(damage/2);note(`Bloqueio normal: ${damage} de dano restante.`)}else note(`Bloqueio falhou (D6: ${n}).`)}else if(kind==='block'&&m.pierce)note('QUEBRA DE ARMADURA ignora o bloqueio.');
if(damage>0){applyDamage(t,damage,!!m.pierce);note(`${chars[t.id].name} sofreu ${damage} de dano.`)}if(damage>0){if(m.id==='melhor')p.burn=10;if(m.id==='corte')p.bleed=20;if(m.id==='kraken')t.passiveDisabled=true}if(m.id==='pente'&&damage>0)p.fugaReady=true;if(m.id==='puxao'&&damage===0)p.combo=0;if(m.id==='mid'&&damage===0)p.combo=0;if(t.hp<=0){end(p);return}
game.pending=null;game.phase='action';if(perfect&&!x.free){game.turn=game.players.indexOf(t);game.freeReturn=game.turn;note('Contra-ataque gratuito: escolha um golpe; sua ação normal virá depois.');render();if(game.turn===1)delayed(aiAct);return}if(x.free){const ret=game.freeReturn;game.freeReturn=null;game.turn=ret??game.players.indexOf(p);render();if(game.turn===1)delayed(aiAct);return}finishTurn()}
function finishTurn(){game.phase='action';game.turn=1-game.turn;if(game.turn===0)game.round++;render();if(game.turn===1&&!game.ended)delayed(aiAct)}
function end(winner){game.ended=true;game.phase='end';note(`${winner===game.players[0]?'VITÓRIA!':'DERROTA!'} ${chars[winner.id].name} venceu.`);render()}
function action(type){if(locked||game.ended)return;if(type==='block'||type==='take'||type==='escape'){resolveDefense(type);return}const p=active();if(type==='pass'){game.freeReturn=null;note('Contra-ataque dispensado. Seu turno normal continua.');render()}else if(type==='reload'){p.res=8;note(`${chars[p.id].name} restaurou toda a ${chars[p.id].resource}.`);finishTurn()}else if(type==='tactical'&&p.fugaReady&&!p.fugaUsed&&p.escapes>0){p.escapes--;p.fugaUsed=true;p.miraReady=true;p.evasion=true;note('FUGA TÁTICA: próximo golpe contra Felphs será evitado. Mira Fria liberada. Resta uma Fuga a menos.');finishTurn()}else if(type==='mira'&&p.miraReady&&!p.miraUsed&&!p.passiveDisabled){p.miraUsed=true;p.miraReady=false;applyDamage(other(),80,false);note('MIRA FRIA: quatro tiros Anti Fuga de 20 de dano (80 total).');if(other().hp<=0)end(p);else finishTurn()}}
function delayed(fn){locked=true;setTimeout(()=>{locked=false;if(game&&!game.ended)fn()},650)}
function aiAct(){if(!game||game.turn!==1||game.phase!=='action')return;const p=active(),free=game.freeReturn!==undefined&&game.freeReturn!==null;const choices=chars[p.id].moves.filter(m=>canUse(p,m));const m=choices.find(x=>x.id==='final')||choices.find(x=>x.id==='mid')||choices[Math.floor(Math.random()*choices.length)];if(m)attack(p,other(),m,free);else if(free){game.freeReturn=null;note('Oponente não tinha recurso para contra-atacar.');delayed(aiAct)}else{p.res=8;note('Oponente restaurou o recurso.');finishTurn()}}
function aiDefend(){const x=game.pending;if(!x||game.phase!=='defend')return;if(x.target.evasion&&!x.antiFuga){x.target.evasion=false;resolveDefense('tacticalEvade');return}resolveDefense(x.move.pierce?'take':Math.random()<.8?'block':'take')}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{const k=b.dataset.mode;if(k==='sound'){sound=!sound;popup(`<h2>SOM ${sound?'ATIVADO':'DESATIVADO'}</h2><p>Os efeitos sonoros serão adicionados quando os arquivos de áudio estiverem disponíveis.</p>`);return}if(k==='fullscreen'){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();return}if(k==='settings'){popup('<h2>CONFIGURAÇÕES</h2><p>Use a tela cheia no botão do menu. O jogo funciona também em celular.</p>');return}if(['online','online-ffa','ranked','login','register','ranking'].includes(k)){popup(`<h2>${{online:'ONLINE 1v1','online-ffa':'ONLINE FFA',ranked:'RANQUEADO',login:'ENTRAR',register:'CRIAR CONTA',ranking:'RANKING'}[k]}</h2><p>Essa função requer servidor e contas de jogadores. O modo offline já está disponível nesta versão.</p>`);return}mode=k;$('mode-label').textContent=k==='training'?'TREINAMENTO CONTRA O BOT':k==='ffa'?'FFA LOCAL: dois personagens disponíveis; confronto 1v1 nesta versão.':'OFFLINE 1v1 CONTRA O BOT';initRoster();show('select')});
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('start').onclick=start;$('restart').onclick=start;$('close-modal').onclick=()=>$('modal').hidden=true;$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').hidden=true};$('help').onclick=()=>popup('<h2>REGRAS DO D6</h2><p>Atirador: 1–3 erra; 4–5 acerta; 6 dobra o dano do golpe.</p><p>Bloqueio: 1–3 falha; 4–5 reduz o dano pela metade; 6 anula o dano e concede um contra-ataque gratuito. O contra-ataque gasta recurso, mas preserva o turno normal.</p><p>Quebra de Armadura atravessa defesa e ignora bloqueio. Fôlego e Recarregar restauram o recurso a 8 e gastam o turno.</p>');
